[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
doubleornothing = "7BphZadCBnMT1duPMHzsE92sYeBp6myuTREceF3bajdf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/puayjianjun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
